platform :ios, '13.0'

pod 'CryptoSwift', '~> 1.0'
pod 'Alamofire', '~> 5.9.0'

pod 'SwiftyJSON'

target 'captcha_swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for captcha_swift

end
